### PR TITLE
Refactor interceptor code 

### PR DESCRIPTION
**Pull request by MathuraMG**
The interceptors now have the following class structure
- BaseInterceptor
   - TextInterceptor
   -  GridInterceptor

and the entities ( p5 functions ) have the following class structure
- BaseEntity
   - BackgroundEntity
   - FillEntity
   - TextEntity
   - ShapeEntity
etc..

### CODE REVIEW

**Comment by catarak** [comment]
Looks great! This is a huge step in the right direction. A few comments:

* I would change the `for` loops to use `Array.forEach`. Especially now, I think it's more JS conventional to lean towards functional style rather than C style. 
* For the `baseInterceptor`/`gridInterceptor`/`soundInterceptor`/`textInterceptor`, I would define all of the instance functions on the `prototype` rather than the class, e.g.
```javascript
baseInterceptor.prototype.getColorName = function(arguments) {
...
}
```
* I thought for a while whether it makes more sense to leave the `BaseEntity` as a static class or change it into a singleton class. I was reading about conventions for static classes and it seems like they're used more for utility functions, e.g. `Math.cos()` ([read more here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes#Static_methods)). Maybe in this case, you want
  - A `BaseEntity`, which is a base class and contains methods that all entities should have
  - Singleton classes that inherit from the `BaseEntity`, such as the `FillEntity`
  - An entity manager, which holds all of the instantiated entities, and registers all of then when an instance of the entity manager is created. 
* This is outside the scope of this PR, but eventually maybe it would make sense to minify everything into one file, and then once the library is imported, create an instance of a singleton class with some configuration based on the mode. Then, to change the mode, you can call a function on that instance to change the mode. 

Let me know if you have any questions! Happy to hop on a Hangout to talk through any of this.

**Comment by MathuraMG** [comment]
Thanks @catarak , will have a look at these and update!

**Comment by MathuraMG** [comment]
@catarak - I switched the some of the for loops to forEach and am in the process of switching all of them. However, I did not change the for loops that [contained break statements](https://github.com/MathuraMG/p5-interceptor/blob/master/soundInterceptor/intercept-p5.js#L91).
I also moved the functions to the `prototype` from the class

Currently `textEntity` and `shapeEntity` do inherit from `baseEntity` and `baseEntity` contains the common functions. However, I did not do the same for `fillEntity` and `backgroundEntity` since they do not require separate objects/rows in the output. They have a variable called `isParameter` that differentiates them. 
The registry manager is currently a part of the baseEntity.

To confirm - would you suggest moving this registry out of the baseEntity?

**Comment by catarak** [comment]
- You can actually get similar functionality to `for` loops + `break` statements by using `Array.some`.
- I think what makes sense about moving the registry out of the baseEntity is that it is a nice separation of concerns--one class defines the base behavior, and one class defines which entities are instantiated.

**Comment by catarak** [comment]
your changes are looking great 😄 let me know when you'd like me to take another pass!

**Comment by MathuraMG** [comment]
Will do! I'm fighting away the remaining for loops :)

**Comment by MathuraMG** [comment]
@catarak - I do have a question, there are [some places](https://github.com/MathuraMG/p5-interceptor/blob/master/textInterceptor/interceptor-functions.js#L208) where I the `for` loop in since it's being used for counting. Would it make sense to switch those to `forEach` as well?

**Comment by MathuraMG** [comment]
@catarak - would you mind having a look at the list of new changes when possible :)

Here's a list of all changes - 
* switched out registry to a [separate variable](https://github.com/processing/p5.js-web-editor/pull/240/commits/c1f5dcaa753a997af8bb8a4a17d47e7346f05664) 
* Switched out `for` loops which loop through an array to `forEach`
* Defined instance function in the interceptor in the prototype instead of in the class

cc @CleezyITP

**Comment by catarak** [comment]
This is looking great, and all of the changes you have made so far are great. Maybe it would at this point make sense to merge this in now, and then continue refactoring in another PR. I think there are a few more things you could do to make this even cleaner and more awesome.

**Comment by MathuraMG** [comment]
makes sense, I'll do that.

**Pull request merged**
